### PR TITLE
Copyedit documentation

### LINKED ISSUE #1378: doc: rephrase "Active Detect Hiddenness"?
In https://github.com/SagerNet/sing-box/blob/docs/zh/manual/proxy-protocol/shadowsocks/index.html and similar pages, the security of protocols are defined as:
* Cryptographic Security
* Binary Characteristics
* Active Detect Hiddenness

Some rephrasing seems to be in order. "Active Detect Hiddenness" sticks out the most and should probably be changed to "Resistance to active probes" (the lowercase is intentional). Analogously, maybe "Binary Characteristics" can be changed to "Resistance to binary pattern detection".

The warning

> Even though GFW rarely blocks UDP-based proxies, such protocols actually have far more "

can also be rephrased to "..., such protocols actually have more *detectable* characteristics than TCP based protocols."

### PR DESCRIPTION
**Pull request by Artoria2e5**
Close #1378

### CODE REVIEW

**Comment by nekohasekai** [comment]
Thank you for your contribution. Please rebase and modify the target branch to main-next, then we can continue.

**Comment by Artoria2e5** [comment]
Gonna do it tomorrow.

**Comment by Artoria2e5** [comment]
Not "tomorrow", but done!

**Comment by Artoria2e5** [comment]
hey uh @nekohasekai, I think the comment got lost somewhere on the way. the squash/merge commit is not found on any branch; furthermore, https://github.com/SagerNet/sing-box/blob/dev-next/docs/manual/proxy-protocol/hysteria2.md is clearly the old version.

**Pull request merged**
