### PR TITLE
Multiple config files support

### PR DESCRIPTION
**Pull request by qjebbs**
The PR ports `Multiple config files support` to sing-box, and takes advice from #164.

```bash
sing-box run -c inbound.json -c outbound.json
sing-box run -r -c config_dir
```

### CODE REVIEW

**Comment by nekohasekai** [comment]
Who defines .jsonc?

**Comment by qjebbs** [comment]
Here with in the VSCode, I have to change the extension to `.jsonc` to enable the comments, or it will alert. So I take it as a convention.

image

**Comment by qjebbs** [comment]
But as to the PR, it allows comment even if the extenstion is `.json`

**Comment by qjebbs** [comment]
Force pushed to apply refactored version of `qjebbs/go-jsons`, which:

- has `100.0%` test coverage for the core `merge` package
- the other `60.3%` coverage is because of the missing tests for codes who load & merge from files

```sh
$ make test
ok      github.com/qjebbs/go-jsons      0.234s  coverage: 60.3% of statements
ok      github.com/qjebbs/go-jsons/merge        0.241s  coverage: 100.0% of statements
```

**Comment by qjebbs** [comment]
`100.0%` test coverage for `qjebbs/go-jsons`:

```sh
$ make test
ok      github.com/qjebbs/go-jsons      0.641s  coverage: 100.0% of statements
ok      github.com/qjebbs/go-jsons/merge        0.360s  coverage: 100.0% of statements
```

**Comment by qjebbs** [comment]
Sorry the branch is deleted accidentally when I tried to squash commits. 

If you want it any time, contact me to recreate the PR or find it at: https://github.com/qjebbs/sing-box/tree/provider

**Pull request closed without merging**
