### PR TITLE
Add a replacement of default geosite.db

### PR DESCRIPTION
**Pull request by Johnshall**

### CODE REVIEW

**Comment by nekohasekai** [comment]
It's not the same format.

**Comment by Johnshall** [comment]
Maybe https://github.com/Johnshall/sing-geosite/ could parse the domainMap into the right format?
It works on my laptop.

**Comment by nekohasekai** [comment]
Submit an issue to Loyalsoldier, I don't provide these support.

**Comment by Johnshall** [comment]
OK. Thanks for your patience.

**Pull request closed without merging**
