### PR TITLE
fix hysteria2 concurrency

### PR DESCRIPTION
**Pull request by Mahdi-zarei**
Fixes hysteria2 multi connection issues by using the mutex for offer and closeWithError, client close now also tells the server to close the stream and server also always closes the stream when it has finished handling it. also handles stream cancelled by local in client.

### CODE REVIEW

**Comment by nekohasekai** [comment]
Since you did not allow edits to this PR, I created the changes myself. Can you check if it fixes this?

**Comment by Mahdi-zarei** [comment]
I tested the dev-next branch and sing-box kept crashing, but I was not able to reproduce the crashes mentioned in #847 using this branch.

p.n: how can I allow edits to this pr? I already have marked Allow edits by maintainers

**Comment by Mahdi-zarei** [comment]
I force pushed the branch once more to fix the stream cancelled by local in client read.

**Comment by nekohasekai** [comment]
No crash logs are provided in #847, and neither do you.

**Comment by nekohasekai** [comment]
Try https://github.com/SagerNet/sing-box/commit/1d6cdb10d0ea13991bd17c0d34eb4d34a4369358

**Comment by Mahdi-zarei** [comment]
> Try [1d6cdb1](https://github.com/SagerNet/sing-box/commit/1d6cdb10d0ea13991bd17c0d34eb4d34a4369358

It seems to have solved the problem. I didn't manage to reproduce any of the previous problems.

**Pull request closed without merging**
