### PR TITLE
Add MTProto inbound

### PR DESCRIPTION
**Pull request by H1JK**

### CODE REVIEW

**Comment by nekohasekai** [comment]
Please update the documentation.

**Comment by hiddify1** [comment]
Great 
Just one optimization question?

Current implementation, try to parse client hello with all of the users. Assume when we have 1000 users, it will have a performance issue.
can we fix it?

**Comment by H1JK** [comment]
@hiddify1 I have pointed out that _MTProto multi-user inbound might be poor on performance limited to its authentication algorithm_ in the document. Unfortunately authentication for multiple users cannot be optimized, it essentially brute force tries all the secrets to find the one that matches the mac, so this process can be very slow in the case of a large number of inbound users. It faces similar issues with Shadowsocks AEAD (2017), VMess Legacy/AEAD with multi-user inbound.

You can share a secret with multiple actual users. The use of multi-user inbound of such protocols should be minimized as much as possible.

**Comment by hiddify1** [comment]
Thank you for your explanation.

**Comment by nekohasekai** [comment]
Since the protocol is exclusive to Telegram and doesn't make sense for anti-censorship purposes right now, we don't maintain such code.

**Pull request closed without merging**
