### PR TITLE
new: add KDE set system proxy support

### PR DESCRIPTION
**Pull request by hiddify-com**
This PR will resolve set system proxy in KDE.

### CODE REVIEW

**Comment by hiddify1** [comment]
Thank you for your comment. I have fixed the HTTPS and FTP proxy. 
However, for KDE6 i did not found any documentation and i do not have it also. I think we can fix it when KDE6 is released.

**Review by nekohasekai — APPROVED** [review]

**Comment by nekohasekai** [comment]
I thought this PR might not have run on a real device because I remembered that KDE5 actually includes gsettings.

**Comment by hiddify-com** [comment]
I do not have KDE but my friend told me that the previous code won't set proxy in KDE but this code does

**Comment by hiddify-com** [comment]
if it change to "Proxy Settings" the terminal command will take it as two argument and it will creates an error

**Comment by nekohasekai** [comment]
> I do not have KDE but my friend told me that the previous code won't set proxy in KDE but this code does

I don't think logically it will work, at least not the one you submitted. Next time I will check PRs more strictly.

**Pull request merged**
