### PR TITLE
Multiple config files & formats support

### PR DESCRIPTION
**Pull request by qjebbs**
The PR ports `Multiple config files formats support` to sing-box which is committed here: https://github.com/v2fly/v2ray-core/pull/451

```
> ./sing-box  
Usage:
  sing-box [command]

Available Commands:
  check       Check configuration
  completion  Generate the autocompletion script for the specified shell
  format      Format configuration
  help        Help about any command
  run         Run service
  version     Print current version of sing-box

Flags:
  -c, --config stringArray     set configuration files / directories (default [config.json])
      --config-format string   configuration files format: auto, json, jsonc, yaml, toml (default "auto")
  -r, --config-recursive       load configuration directories recursively
  -D, --directory string       set working directory
      --disable-color          disable color output
  -h, --help                   help for sing-box
```

### CODE REVIEW

**Comment by nekohasekai** [comment]
Thanks for your work, but no serious application needs configuration files in multiple formats, especially adding support in the form of duplicating a lot of code.

**Comment by qjebbs** [comment]
It's important for users like me, who works with only one `sing-box` binary.

I'm running lots of services:

image

Different service all have their own `inbound`, `outbound`, `rules`, it can be a mess if they're all mixed up together.

with multi-files support, I can put them in separated files, and plug & unplug by move files.

**Comment by nekohasekai** [comment]
I think you can create a standalone json merge library.

**Comment by nekohasekai** [comment]
The json comment filter you called jsonc has already been applied by version 1.1.

**Pull request closed without merging**
