### PR TITLE
leastload and leastping Balancers

### PR DESCRIPTION
**Pull request by qjebbs**
The PR ports the `leastload` and`leastping` balancers to `sing-box`,  which were committed here: https://github.com/v2fly/v2ray-core/pull/589

Please see document files in the PR for detail.

### Preview

config:

```
{
  "tag": "leastload",
  "type": "leastload",
  "outbounds": [
    "all"
  ],
  "fallback": "block"
  "pick": {
    "expected": 5
  }
}
```

log:

```
INFO[0051] [3846517800] inbound/socks[socks-in]: inbound connection from 127.0.0.1:65052
INFO[0051] [3846517800] inbound/socks[socks-in]: [] inbound connection to xxxx:5228
DEBUG[0051] [3846517800] router: match[0] inbound=socks-in => leastload
DEBUG[0051] [3846517800] outbound/leastload[leastload]: (network=tcp, candidates=5) => [all.outboud-3] +W=88.053871ms STD=88.053871ms AVG=651.090064ms Fail=0/10
INFO[0051] [3846517800] outbound/direct[all.outboud-3]: outbound connection to xxxx:5228
```

### CODE REVIEW

**Comment by qjebbs** [comment]
Closed due to conceptually incompatible.

`sing-box`'s `adapter.OutboundGroup` is the most simillar concepet to the `leastload` balancer. 

- `adapter.OutboundGroup` works like this: `group of outbounds` --> `single outbound`
- `leastload` focuses on find best nodes to connect to and select as many nodes as possible for bandwidth reasons, which is: `group of outbounds` -> `qulified nodes` -> `random`

This is a conceptually incompatible design, and I ended up with `tracker` problem:

1. `trafficontrol.NewTCPTracker()` asks `leastload` for `Now()` tag, it picks a random qualified nodes and returns its tag.
1. later, `leastload` is asked to select a node for a new connection, it again picks another random qualified nodes.

It's not quaranteed that the two nodes are the same one, no easy ways to solve the problem.

PS: For my personal use, I simply ignore the tracker problem.

**Comment by y1rn** [comment]
Is there any load balance like config examples?

**Comment by y1rn** [comment]
> > Is there any load balance like config examples?
> 
> [qjebbs/sing-box](https://github.com/qjebbs/sing-box)

thx, but I'm ios user. I will try until I have other platform.

**Comment by jxph1123** [comment]
Can you transplant the `leastping` function, thank you

**Pull request closed without merging**
