### PR TITLE
Fix windows proxy

### PR DESCRIPTION
**Pull request by isnowly**
Fix idm does't recognize the system proxy, and LAN segment bypass.

### CODE REVIEW

**Comment by nekohasekai** [comment]
Can you explain what removing 'http' does?

**Comment by isnowly** [comment]
Hi, @nekohasekai 

The default proxy protocol of the Windows system is `http`. `http://127.0.0.1` is valid in most cases, but it cannot work in some software, for example: `IDM (internate download manager)`. So I thought compatibility would be better without `http://`, I tested it and it works. At the same time, I refer to `clash` and other software, none of them add `http://` prefix.

image



Thanks.

**Comment by database64128** [comment]
If you set the system proxy via the Settings app or Internet Options, the `http://` prefix will be automatically added. I think it's best for sing-box to align with the system's default behavior.

If you purchased IDM, you should ask the IDM developers to fix this bug. Or just specify the proxy manually in IDM's configuration.

**Comment by isnowly** [comment]
> If you set the system proxy via the Settings app or Internet Options, the `http://` prefix will be automatically added. I think it's best for sing-box to align with the system's default behavior.
> 
> If you purchased IDM, you should ask the IDM developers to fix this bug. Or just specify the proxy manually in IDM's configuration.

By default, the system does't add the `http://` prefix. You only need to manually set the Windows system proxy, then open the Windows registry, and find the value of `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer` without the `http://` prefix.

BTW, there is nothing wrong with IDM's default behavior.

**Comment by isnowly** [comment]
> If you set the system proxy via the Settings app or Internet Options, the `http://` prefix will be automatically added. I think it's best for sing-box to align with the system's default behavior.
> 
> If you purchased IDM, you should ask the IDM developers to fix this bug. Or just specify the proxy manually in IDM's configuration.

By default, the system does not add the `http://` prefix. To find out the default behavior of Windows, you only need to manually set the Windows system proxy, then open the Windows registry, find the `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer` key, and then you can look at the value to know the conclusion.

The default proxy protocol of windows is http, but there is no need to specify `http://` prefix

BTW, there is nothing wrong with IDM's default behavior.

**Comment by database64128** [comment]
> By default, the system does not add the `http://` prefix. To find out the default behavior of Windows, you only need to manually set the Windows system proxy, then open the Windows registry, find the `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer` key, and then you can look at the value to know the conclusion.

That's not the case on my Windows 11 system. I only posted my reply because that's how it works on my system. And so far I have encountered exactly 0 programs that have issues with this.

> BTW, there is nothing wrong with IDM's default behavior.

If it doesn't work, then something's wrong with it.

**Comment by isnowly** [comment]
> That's not the case on my Windows 11 system. I only posted my reply because that's how it works on my system. And so far I have encountered exactly 0 programs that have issues with this.

image

image

What did you see?


> If it doesn't work, then something's wrong with it.

IDM may be able to do better, but for now it's playing by the rules. It's okay to follow the rules, right?

**Comment by isnowly** [comment]
In conclusion, `http://<ip>:<port>` is fine in most cases, but some software will make mistakes. To fix it just remove the `http://` prefix. This doesn't affect otherwise working software, and it conforms to Windows default behavior.

**Comment by database64128** [comment]
> but for now it's playing by the rules.

Clearly it's not. Otherwise it would've worked.

> What did you see?

I use `localhost` instead of `127.0.0.1` as the proxy address. That's probably why the system prepended `http://`.

**Comment by isnowly** [comment]
> I use `localhost` instead of `127.0.0.1` as the proxy address. That's probably why the system prepended `http://`.

My conclusion after verification is not as you said.

image

localhost and 127.0.0.1 make no difference in this case.

**Comment by database64128** [comment]
OK. I just double-checked and found out the culprit is Internet Options. Opening Internet Options would add the `http://` prefix if it wasn't already there.

**Review by database64128 — APPROVED** [review]

**Comment by isnowly** [comment]
@database64128 Can you tell me the steps to reproduce? Thanks.

**Comment by database64128** [comment]
On my system, simply opening Internet Options would change `localhost:8080` to `http://localhost:8080`.

**Comment by nekohasekai** [comment]
The official example provides the prefix, so the problem should be in the application that does not work.

https://learn.microsoft.com/en-us/windows/win32/wininet/setting-and-retrieving-internet-options#setting-connection-options

**Comment by nekohasekai** [comment]
> For proxy exception, some users may want to customize it (e.g. bypassing `localhost.ptlogin2.qq.com`). How about leaving it as is (do not override it on starting/stopping)?

e8ed4b4570e49d06013e83d4d06758e8720225ba

**Comment by isnowly** [comment]
> The official example provides the prefix, so the problem should be in the application that does not work.
> 
> https://learn.microsoft.com/en-us/windows/win32/wininet/setting-and-retrieving-internet-options#setting-connection-options


Hi, @nekohasekai 

I think we have a difference between Windows and Wininet as a standard.  Windows is the protagonist.  We should take Windows default behavior as standard.  I refer to clash and shadowsocks and v2rayN, their format is `host:port` instead of `http://host:port`.

**Comment by nekohasekai** [comment]
I think we still need something standard, something that comes from documentation rather than behavior from your device or some closed source 3rd party software that you like. Please show your code.

**Comment by isnowly** [comment]
PR closed.  Thank you everyone!

**Comment by isnowly** [comment]
PR closed.  Thanks everyone!

**Pull request closed without merging**
