### PR TITLE
Add TLS Fragmentation

### PR DESCRIPTION
**Pull request by kyochikuto**
This PR ports a feature from Xray that is used to fragment TLS clientHello packets to circumvent TLS-based blockings (mostly seen in Iran's firewall).

Credits:
@GFW-knocker for the idea.
@rrouzbeh for his implementation in [tlsx]([rrouzbeh](https://github.com/projectdiscovery/tlsx/commits?author=rrouzbeh))
@sambali9 for his implementation in Xray.

### CODE REVIEW

**Comment by kyochikuto** [comment]
Needless to say, this has been tested and it effectively unblocks YouTube and Twitter in Iran which are blocked by TLS methods.

**Comment by hiddify-com** [comment]
Great Job

**Comment by hiddify-com** [comment]
I suggest you to rebase your branch with the latest git so the reviewers can better understand the changes and it will accelerate the review process

**Comment by kyochikuto** [comment]
@nekohasekai is there something holding this back from a merge? If any changes are needed let me know please so we can go ahead with this much needed feature in Iran.

**Comment by realartin** [comment]
good job

**Comment by ImMohammad20000** [comment]
Great Job

**Comment by nekohasekai** [comment]
From what I understand, this is a little trick that only works in Iran and can easily break; in the Xray discussion, the original author didn't agree with this feature. Since there is no such research to refer to, and your code and design do not match the style of sing-box, we are not ready to merge this intrusive update for the time being. I recommend that you make and release a fork.

**Comment by nekohasekai** [comment]
It's a pity that I don't have the energy to provide pro bono research and coding services to the Iranian end-user community where there is no community. If you want sing-box to accept and maintain code that differs significantly from our style, this requires some professional justification.

**Comment by kyochikuto** [comment]
> It's a pity that I don't have the energy to provide pro bono research and coding services to the Iranian end-user group where there is no community. If you want sing-box to accept and maintain code that differs significantly from our style, this requires some professional justification.

No one wanted you to provide services, hence this being a PR! Someone asked for this in #823 and you labeled it as "pull request welcome" and here we are...

And I did not find any PR submission templates stating design and style! Please point it out so I can see what you mean exactly by "our style" because the commits are following best practices of Go programming as far as I'm concerned adding only 4 files and removing only 1.

You can read about the idea on [https://github.com/GFW-knocker/gfw_resist_tls_proxy](https://github.com/GFW-knocker/gfw_resist_tls_proxy) and I can not provide you anymore proof than user testimonies and a testing machine

**Comment by nekohasekai** [comment]
> No one wanted you to provide services, hence this being a PR! 

Submitting a PR does require maintainers to maintain your code, and I'm not satisfied with the code you're very confident in, that's all.

**Pull request closed without merging**
